dist: xenial
language: python
python:
  - 2.7
  - pypy
  - 3.5
  - 3.6
  - 3.7
  - pypy3
install:
  - pip install -U pip setuptools
  - pip install -U coveralls coverage
  - pip install -U -e ".[test]"
cache: pip
script:
  - coverage run -m zope.testrunner --test-path=src  --auto-color
after_success:
  - coverage report
  - coveralls
before_cache:
    - rm -f $HOME/.cache/pip/log/debug.log
