dist: xenial
language: python
python:
  - "pypy"
  - "pypy3"
  - "3.7"
  - "3.6"
  - "3.5"
  - "2.7"
install:
  - python setup.py develop
  - pip install nose coverage
script:
  nosetests --with-coverage --cover-package=perfmetrics --cover-branches
